export const ROUTES = {
  home: "/",
  catalogo: "/catalogo",
  catalogoCategory: (slug: string) => `/catalogo/${slug}`,
  sobreNosotros: "/sobre-nosotros",
  nuestraHistoria: "/nuestra-historia",
  lookbook: "/lookbook",
  colaboraciones: "/colaboraciones",
  blog: "/blog",
  blogPost: (slug: string) => `/blog/${slug}`,
  contacto: "/contacto",
  envios: "/envios",
  devoluciones: "/devoluciones",
  guiaDeTallas: "/guia-de-tallas",
  faq: "/faq",
  loUltimo: "/#lo-ultimo",
  catalogoAnchor: "/#catalogo",
  // Auth
  login: "/login",
  registro: "/registro",
  recuperarPassword: "/recuperar-password",
  nuevaPassword: "/nueva-password",
  // Cuenta
  cuenta: "/cuenta",
  pedidos: "/cuenta/pedidos",
  direcciones: "/cuenta/direcciones",
  // Admin
  admin: "/admin",
  adminProductos: "/admin/productos",
  adminPedidos: "/admin/pedidos",
  favoritos: "/favoritos",
} as const;
