export type Province = {
  name: string;
  districts: string[];
};

export type Department = {
  name: string;
  provinces: Province[];
};

export const departments: Department[] = [
  {
    name: "Amazonas",
    provinces: [
      { name: "Chachapoyas", districts: ["Chachapoyas", "Asunción", "Balsas", "Cheto", "Chiliquín", "Chuquibamba", "Granada", "Huancas", "La Jalca", "Leimebamba", "Levanto", "Magdalena", "Mariscal Castilla", "Molinopampa", "Montevideo", "Olleros", "Quinjalca", "San Francisco de Daguas", "San Isidro de Maino", "Soloco", "Sonche"] },
      { name: "Bagua", districts: ["Bagua", "Aramango", "Copallín", "El Parco", "Imaza", "La Peca"] },
      { name: "Bongará", districts: ["Jumbilla", "Chisquilla", "Churuja", "Corosha", "Cuispes", "Florida", "Jazán", "Recta", "San Carlos", "Shipasbamba", "Valera", "Yambrasbamba"] },
      { name: "Condorcanqui", districts: ["Nieva", "El Cenepa", "Río Santiago"] },
      { name: "Luya", districts: ["Lámud", "Camporredondo", "Cocabamba", "Colcamar", "Conila", "Inguilpata", "Longuita", "Lonya Chico", "Luya", "Luya Viejo", "María", "Ocallí", "Ocumal", "Pisuquía", "Providencia", "San Cristóbal", "San Francisco del Yeso", "San Jerónimo", "San Juan de Lopecancha", "Santa Catalina", "Santo Tomás", "Tingo", "Trita"] },
      { name: "Rodríguez de Mendoza", districts: ["Mendoza", "Chirimoto", "Cochamal", "Huambo", "Limabamba", "Longar", "Mariscal Benavides", "Milpuc", "Omia", "San Nicolás", "Santa Rosa", "Totora", "Vista Alegre"] },
      { name: "Utcubamba", districts: ["Bagua Grande", "Cajaruro", "Cumba", "El Milagro", "Jamalca", "Lonya Grande", "Yamón"] },
    ],
  },
  {
    name: "Áncash",
    provinces: [
      { name: "Huaraz", districts: ["Huaraz", "Cochabamba", "Colcabamba", "Huanchay", "Independencia", "Jangas", "La Libertad", "Olleros", "Pampas Grande", "Pariacoto", "Pira", "Tarica"] },
      { name: "Aija", districts: ["Aija", "Coris", "Huacllán", "La Merced", "Succha"] },
      { name: "Antonio Raymondi", districts: ["Llamellín", "Aczo", "Chaccho", "Chingas", "Mirgas", "San Juan de Rontoy"] },
      { name: "Asunción", districts: ["Chacas", "Acochaca"] },
      { name: "Bolognesi", districts: ["Chiquián", "Abelardo Pardo Lezameta", "Antonio Raymondi", "Aquia", "Cajacay", "Canis", "Colquioc", "Huallanca", "Huasta", "Huayllacayán", "La Primavera", "Mangas", "Pacllón", "San Miguel de Corpanqui", "Ticllos"] },
      { name: "Carhuaz", districts: ["Carhuaz", "Acopampa", "Amashca", "Anta", "Ataquero", "Marcará", "Pariahuanca", "San Miguel de Aco", "Shilla", "Tinco", "Yungar"] },
      { name: "Carlos Fermín Fitzcarrald", districts: ["San Luis", "San Nicolás", "Yauya"] },
      { name: "Casma", districts: ["Casma", "Buena Vista Alta", "Comandante Noel", "Yaután"] },
      { name: "Corongo", districts: ["Corongo", "Aco", "Bambas", "Cusca", "La Pampa", "Yanac", "Yupán"] },
      { name: "Huari", districts: ["Huari", "Anra", "Cajay", "Chavín de Huántar", "Huacachi", "Huacchis", "Huachis", "Huántar", "Masin", "Paucas", "Pontó", "Rahuapampa", "Rapayán", "San Marcos", "San Pedro de Chaná", "Uco"] },
      { name: "Huarmey", districts: ["Huarmey", "Cochapeti", "Culebras", "Huayán", "Malvas", "Santiago de Chilcayoc"] },
      { name: "Huaylas", districts: ["Caraz", "Huallanca", "Huata", "Huaylas", "Mato", "Pamparomás", "Pueblo Libre", "Santa Cruz", "Santo Toribio", "Yuracmarca"] },
      { name: "Mariscal Luzuriaga", districts: ["Piscobamba", "Casca", "Eleazar Guzmán Barrón", "Fidel Olivas Escudero", "Llama", "Llumpa", "Lucma", "Musga"] },
      { name: "Ocros", districts: ["Ocros", "Acas", "Cajamarquilla", "Carhuapampa", "Cochas", "Congas", "Llipa", "San Cristóbal de Raján", "San Pedro", "Santiago de Chilcas"] },
      { name: "Pallasca", districts: ["Cabana", "Bolognesi", "Conchucos", "Huacaschuque", "Huandoval", "Lacabamba", "Llapo", "Pallasca", "Pampas", "Santa Rosa", "Tauca"] },
      { name: "Pomabamba", districts: ["Pomabamba", "Huayllán", "Parobamba", "Quinuabamba"] },
      { name: "Recuay", districts: ["Recuay", "Cátac", "Cotaparaco", "Huayllapampa", "Llacllín", "Marca", "Pampas Chico", "Pararín", "Tapacocha", "Ticapampa"] },
      { name: "Santa", districts: ["Chimbote", "Cáceres del Perú", "Coishco", "Macate", "Moro", "Nepeña", "Nuevo Chimbote", "Samanco", "Santa"] },
      { name: "Sihuas", districts: ["Sihuas", "Acobamba", "Alfonso Ugarte", "Cashapampa", "Chingalpo", "Huayllabamba", "Quiches", "Ragash", "San Juan", "Sicsibamba"] },
      { name: "Yungay", districts: ["Yungay", "Cascapara", "Mancos", "Matacoto", "Quillo", "Ranrahirca", "Shupluy", "Yanama"] },
    ],
  },
  {
    name: "Apurímac",
    provinces: [
      { name: "Abancay", districts: ["Abancay", "Chacoche", "Circa", "Curahuasi", "Huanipaca", "Lambrama", "Pichirhua", "San Pedro de Cachora", "Tamburco"] },
      { name: "Andahuaylas", districts: ["Andahuaylas", "Andarapa", "Chiara", "Huancarama", "Huancaray", "Huayana", "Kaquiabamba", "Kishuará", "Pacobamba", "Pacucha", "Pampachiri", "Pomacocha", "San Antonio de Cachi", "San Jerónimo", "San Miguel de Chaccrampa", "Santa María de Chicmo", "Talavera", "Tumay Huaraca", "Turpo"] },
      { name: "Antabamba", districts: ["Antabamba", "El Oro", "Huaquirca", "Juan Espinoza Medrano", "Oropesa", "Pachaconas", "Sabaino"] },
      { name: "Aymaraes", districts: ["Chalhuanca", "Capaya", "Caraybamba", "Chapimarca", "Colcabamba", "Cotaruse", "Huayllo", "Justo Apu Sahuaraura", "Lucre", "Pocohuanca", "San Juan de Chacña", "Sañayca", "Soraya", "Tapairihua", "Tintay", "Toraya", "Yanaca"] },
      { name: "Cotabambas", districts: ["Tambobamba", "Challhuahuacho", "Cotabambas", "Coyllurqui", "Haquira", "Mara"] },
      { name: "Chincheros", districts: ["Chincheros", "Anco Huallo", "Cocharcas", "Huaccana", "Ocobamba", "Ongoy", "Ranracancha", "Uranmarca"] },
      { name: "Grau", districts: ["Chuquibambilla", "Curpahuasi", "Gamarra", "Huayllati", "Mamara", "Micaela Bastidas", "Pataypampa", "Progreso", "San Antonio", "Santa Rosa", "Turpay", "Vilcabamba", "Virundo", "Curasco"] },
    ],
  },
  {
    name: "Arequipa",
    provinces: [
      { name: "Arequipa", districts: ["Arequipa", "Alto Selva Alegre", "Cayma", "Cerro Colorado", "Characato", "Chiguata", "Jacobo Hunter", "José Luis Bustamante y Rivero", "La Joya", "Mariano Melgar", "Miraflores", "Mollebaya", "Paucarpata", "Pocsi", "Polobaya", "Quequeña", "Sabandía", "Sachaca", "San Juan de Siguas", "San Juan de Tarucani", "Santa Isabel de Siguas", "Santa Rita de Siguas", "Socabaya", "Tiabaya", "Uchumayo", "Vítor", "Yanahuara", "Yarabamba", "Yura"] },
      { name: "Camaná", districts: ["Camaná", "José María Quimper", "Mariano Nicolás Valcárcel", "Mariscal Cáceres", "Nicolás de Piérola", "Ocoña", "Quilca", "Samuel Pastor"] },
      { name: "Caravelí", districts: ["Caravelí", "Acarí", "Atico", "Atiquipa", "Bella Unión", "Cahuacho", "Chala", "Chaparra", "Huanuhuanu", "Jaqui", "Lomas", "Quicacha", "Yauca"] },
      { name: "Castilla", districts: ["Aplao", "Andagua", "Ayo", "Chachas", "Chilcaymarca", "Choco", "Huancarqui", "Machaguay", "Orcopampa", "Pampacolca", "Tipán", "Uñón", "Uraca", "Viraco"] },
      { name: "Caylloma", districts: ["Chivay", "Achoma", "Cabanaconde", "Callalli", "Caylloma", "Coporaque", "Huambo", "Huanca", "Ichupampa", "Lari", "Lluta", "Maca", "Madrigal", "Majes", "San Antonio de Chuca", "Sibayo", "Tapay", "Tisco", "Tuti", "Yanque"] },
      { name: "Condesuyos", districts: ["Chuquibamba", "Andaray", "Cayarani", "Chichas", "Iray", "Río Grande", "Salamanca", "Yanaquihua"] },
      { name: "Islay", districts: ["Mollendo", "Cocachacra", "Dean Valdivia", "Islay", "Mejía", "Punta de Bombón"] },
      { name: "La Unión", districts: ["Cotahuasi", "Alca", "Charcana", "Huaynacotas", "Pampamarca", "Puyca", "Quechualla", "Sayla", "Tauría", "Tomepampa", "Toro"] },
    ],
  },
  {
    name: "Ayacucho",
    provinces: [
      { name: "Huamanga", districts: ["Ayacucho", "Acocro", "Acos Vinchos", "Carmen Alto", "Chiara", "Jesús Nazareno", "Ocros", "Pacaycasa", "Quinua", "San José de Ticllas", "San Juan Bautista", "Santiago de Pischa", "Socos", "Tambillo", "Vinchos"] },
      { name: "Cangallo", districts: ["Cangallo", "Chuschi", "Los Morochucos", "María Parado de Bellido", "Paras", "Totos"] },
      { name: "Huanca Sancos", districts: ["Sancos", "Carapo", "Sacsamarca", "Santiago de Lucanamarca"] },
      { name: "Huanta", districts: ["Huanta", "Ayahuanco", "Huamanguilla", "Iguain", "Llochegua", "Luricocha", "Santillana", "Sivia"] },
      { name: "La Mar", districts: ["San Miguel", "Anco", "Ayna", "Chilcas", "Chungui", "Luis Carranza", "Santa Rosa", "Tambo"] },
      { name: "Lucanas", districts: ["Puquio", "Aucará", "Cabana", "Carmen Salcedo", "Chaviña", "Chipao", "Huac-Huas", "Laramate", "Leoncio Prado", "Llauta", "Lucanas", "Ocaña", "Otoca", "Saisa", "San Cristóbal", "San Juan", "San Pedro", "San Pedro de Palco", "Sancos", "Santa Ana de Huaycahuacho", "Santa Lucía"] },
      { name: "Parinacochas", districts: ["Coracora", "Chumpi", "Coronel Castañeda", "Pacapausa", "Pullo", "Puyusca", "San Francisco de Ravacayco", "Upahuacho"] },
      { name: "Paucar del Sara Sara", districts: ["Pausa", "Colta", "Corculla", "Lampa", "Marcabamba", "Oyolo", "Pararca", "San Javier de Alpabamba", "San José de Ushua", "Sara Sara"] },
      { name: "Sucre", districts: ["Querobamba", "Belén", "Chalcos", "Chilcayoc", "Huacaña", "Morcolla", "Paico", "San Pedro de Larcay", "San Salvador de Quije", "Santiago de Paucaray", "Soras"] },
      { name: "Víctor Fajardo", districts: ["Huancapi", "Alcamenca", "Apongo", "Asquipata", "Canaria", "Cayara", "Colca", "Huamanquiquia", "Huancaraylla", "Huaya", "Sarhua", "Vilcanchos"] },
      { name: "Vilcas Huamán", districts: ["Vilcas Huamán", "Accomarca", "Carhuanca", "Concepción", "Huambalpa", "Independencia", "Saurama", "Vischongo"] },
    ],
  },
  {
    name: "Cajamarca",
    provinces: [
      { name: "Cajamarca", districts: ["Cajamarca", "Asunción", "Chetilla", "Cospán", "Encañada", "Jesús", "Llacanora", "Los Baños del Inca", "Magdalena", "Matará", "Namora", "San Juan"] },
      { name: "Cajabamba", districts: ["Cajabamba", "Cachachi", "Condebamba", "Sitacocha"] },
      { name: "Celendín", districts: ["Celendín", "Chumuch", "Cortegana", "Huasmin", "Jorge Chávez", "José Gálvez", "Miguel Iglesias", "Oxamarca", "Sorochuco", "Sucre", "Utco", "La Libertad de Pallán"] },
      { name: "Chota", districts: ["Chota", "Anguía", "Chadín", "Chiguirip", "Chimban", "Choropampa", "Cochabamba", "Conchán", "Huambos", "Lajas", "Llama", "Miracosta", "Paccha", "Pión", "Querocoto", "San Juan de Licupis", "Tacabamba", "Tocmoche"] },
      { name: "Contumazá", districts: ["Contumazá", "Chilete", "Cupisnique", "Guzmango", "San Benito", "Santa Cruz de Toledo", "Tantarica", "Yonán"] },
      { name: "Cutervo", districts: ["Cutervo", "Callayuc", "Choros", "Cujillo", "La Ramada", "Pimpingos", "Querocotillo", "San Andrés de Cutervo", "San Juan de Cutervo", "San Luis de Lucma", "Santa Cruz", "Santo Domingo de la Capilla", "Santo Tomás", "Socota", "Toribio Casanova"] },
      { name: "Hualgayoc", districts: ["Bambamarca", "Chugur", "Hualgayoc"] },
      { name: "Jaén", districts: ["Jaén", "Bellavista", "Chontali", "Colasay", "Huabal", "Las Pirias", "Pomahuaca", "Pucará", "Sallique", "San Felipe", "San José del Alto", "Santa Rosa"] },
      { name: "San Ignacio", districts: ["San Ignacio", "Chirinos", "Huarango", "La Coipa", "Namballe", "San José de Lourdes", "Tabaconas"] },
      { name: "San Marcos", districts: ["Pedro Gálvez", "Chancay", "Eduardo Villanueva", "Gregorio Pita", "Ichocán", "José Manuel Quiroz", "José Sabogal"] },
      { name: "San Miguel", districts: ["San Miguel", "Bolívar", "Calquis", "Catilluc", "El Prado", "La Florida", "Llapa", "Nanchoc", "Niepos", "San Gregorio", "San Silvestre de Cochán", "Tongod", "Unión Agua Blanca"] },
      { name: "San Pablo", districts: ["San Pablo", "San Bernardino", "San Luis", "Tumbaden"] },
      { name: "Santa Cruz", districts: ["Santa Cruz", "Andabamba", "Catache", "Chancaybaños", "La Esperanza", "Ninabamba", "Pulán", "Saucepampa", "Sexi", "Uticyacu", "Yauyucán"] },
    ],
  },
  {
    name: "Callao",
    provinces: [
      { name: "Callao", districts: ["Callao", "Bellavista", "Carmen de la Legua", "La Perla", "La Punta", "Ventanilla", "Mi Perú"] },
    ],
  },
  {
    name: "Cusco",
    provinces: [
      { name: "Cusco", districts: ["Cusco", "Ccorca", "Poroy", "San Jerónimo", "San Sebastián", "Santiago", "Saylla", "Wánchaq"] },
      { name: "Acomayo", districts: ["Acomayo", "Acopia", "Acos", "Mosoc Llacta", "Pomacanchi", "Rondocan", "Sangarará"] },
      { name: "Anta", districts: ["Anta", "Ancahuasi", "Cachimayo", "Chinchaypujio", "Huarocondo", "Limatambo", "Mollepata", "Pucyura", "Zurite"] },
      { name: "Calca", districts: ["Calca", "Coya", "Lamay", "Lares", "Písac", "San Salvador", "Taray", "Yanatile"] },
      { name: "Canas", districts: ["Yanaoca", "Checca", "Kunturkanki", "Langui", "Layo", "Pampamarca", "Quehue", "Túpac Amaru"] },
      { name: "Canchis", districts: ["Sicuani", "Checacupe", "Combapata", "Maranganí", "Pitumarca", "San Pablo", "San Pedro", "Tinta"] },
      { name: "Chumbivilcas", districts: ["Santo Tomás", "Capacmarca", "Chamaca", "Colquemarca", "Livitaca", "Llusco", "Quiñota", "Velille"] },
      { name: "Espinar", districts: ["Yauri", "Condoroma", "Coporaque", "Ocoruro", "Pallpata", "Pichigua", "Suyckutambo"] },
      { name: "La Convención", districts: ["Santa Ana", "Echarate", "Huayopata", "Maranura", "Ocobamba", "Quellouno", "Quimbiri", "Santa Teresa", "Vilcabamba", "Pichari", "Inkawasi", "Villa Virgen", "Villa Kintiarina"] },
      { name: "Paruro", districts: ["Paruro", "Accha", "Ccapi", "Colcha", "Huanoquite", "Omacha", "Paccaritambo", "Pillpinto", "Yaurisque"] },
      { name: "Paucartambo", districts: ["Paucartambo", "Caicay", "Challabamba", "Colquepata", "Huancarani", "Kosñipata"] },
      { name: "Quispicanchi", districts: ["Urcos", "Andahuaylillas", "Camanti", "Ccarhuayo", "Ccatca", "Cusipata", "Huaro", "Lucre", "Marcapata", "Ocongate", "Oropesa", "Quiquijana"] },
      { name: "Urubamba", districts: ["Urubamba", "Chinchero", "Huayllabamba", "Machupicchu", "Maras", "Ollantaytambo", "Yucay"] },
    ],
  },
  {
    name: "Huancavelica",
    provinces: [
      { name: "Huancavelica", districts: ["Huancavelica", "Acobambilla", "Acoria", "Conayca", "Cuenca", "Huachocolpa", "Huayllahuara", "Izcuchaca", "Laria", "Manta", "Mariscal Cáceres", "Moya", "Nuevo Occoro", "Palca", "Pilchaca", "Vilca", "Yauli", "Ascensión"] },
      { name: "Acobamba", districts: ["Acobamba", "Andabamba", "Anta", "Caja", "Marcas", "Paucará", "Pomacocha", "Rosario"] },
      { name: "Angaraes", districts: ["Lircay", "Anchonga", "Callanmarca", "Ccochaccasa", "Chincho", "Congalla", "Huanca-Huanca", "Huayllay Grande", "Julcamarca", "San Antonio de Antaparco", "Santo Tomás de Pata", "Secclla"] },
      { name: "Castrovirreyna", districts: ["Castrovirreyna", "Arma", "Aurahua", "Capillas", "Chupamarca", "Cocas", "Huachos", "Huamatambo", "Mollepampa", "San Juan", "Santa Ana", "Tantara", "Ticrapo"] },
      { name: "Churcampa", districts: ["Churcampa", "Anco", "Chinchihuasi", "El Carmen", "La Merced", "Locroja", "Pachamarca", "Paucarbamba", "San Miguel de Mayocc", "San Pedro de Coris"] },
      { name: "Huaytará", districts: ["Huaytará", "Ayaví", "Córdova", "Huayacundo Arma", "Laramarca", "Ocoyo", "Pilpichaca", "Querco", "Quito-Arma", "San Antonio de Cusicancha", "San Francisco de Sangayaico", "San Isidro", "Santiago de Chocorvos", "Santiago de Quirahuara", "Santo Domingo de Capillas", "Tambo"] },
      { name: "Tayacaja", districts: ["Pampas", "Acostambo", "Acraquia", "Ahuaycha", "Colcabamba", "Daniel Hernández", "Huachocolpa", "Huaribamba", "Ñahuimpuquio", "Pazos", "Quishuar", "Salcabamba", "Salcahuasi", "San Marcos de Rocchac", "Surcubamba", "Tintay Puncu"] },
    ],
  },
  {
    name: "Huánuco",
    provinces: [
      { name: "Huánuco", districts: ["Huánuco", "Amarilis", "Chinchao", "Churubamba", "Margos", "Quisqui", "San Francisco de Cayrán", "San Pedro de Chaulán", "Santa María del Valle", "Yarumayo", "Pillco Marca"] },
      { name: "Ambo", districts: ["Ambo", "Cayna", "Colpas", "Conchamarca", "Huácar", "San Francisco", "San Rafael", "Tomayquichua"] },
      { name: "Dos de Mayo", districts: ["La Unión", "Chuquis", "Marías", "Pachas", "Quivilla", "Ripán", "Shunqui", "Sillapata", "Yanas"] },
      { name: "Huacaybamba", districts: ["Huacaybamba", "Canchabamba", "Cochabamba", "Pinra"] },
      { name: "Huamalíes", districts: ["Llata", "Arancay", "Chavín de Pariarca", "Jacas Grande", "Jircán", "Miraflores", "Monzón", "Punchao", "Puños", "Singa", "Tantamayo"] },
      { name: "Leoncio Prado", districts: ["Rupa-Rupa", "Daniel Alomía Robles", "Hermilio Valdizán", "José Crespo y Castillo", "Luyando", "Mariano Dámaso Beraún"] },
      { name: "Marañón", districts: ["Huacrachuco", "Cholón", "San Buenaventura"] },
      { name: "Pachitea", districts: ["Panao", "Chaglla", "Molino", "Umari"] },
      { name: "Puerto Inca", districts: ["Puerto Inca", "Codo del Pozuzo", "Honoria", "Tournavista", "Yuyapichis"] },
      { name: "Lauricocha", districts: ["Jesús", "Baños", "Jivia", "Queropalca", "Rondos", "San Francisco de Asís", "San Miguel de Cauri"] },
      { name: "Yarowilca", districts: ["Chavinillo", "Aparicio Pomares", "Cahuac", "Chacabamba", "Chupán", "Jacas Chico", "Obas", "Pampamarca"] },
    ],
  },
  {
    name: "Ica",
    provinces: [
      { name: "Ica", districts: ["Ica", "La Tinguiña", "Los Aquijes", "Ocucaje", "Pachacútec", "Parcona", "Pueblo Nuevo", "Salas", "San José de los Molinos", "San Juan Bautista", "Santiago", "Subtanjalla", "Tate", "Yauca del Rosario"] },
      { name: "Chincha", districts: ["Chincha Alta", "Alto Larán", "Chavín", "Chincha Baja", "El Carmen", "Grocio Prado", "Pueblo Nuevo", "San Juan de Yanac", "San Pedro de Huacarpana", "Sunampe", "Tambo de Mora"] },
      { name: "Nazca", districts: ["Nazca", "Changuillo", "El Ingenio", "Marcona", "Vista Alegre"] },
      { name: "Palpa", districts: ["Palpa", "Llipata", "Río Grande", "Santa Cruz", "Tibillo"] },
      { name: "Pisco", districts: ["Pisco", "Huancano", "Humay", "Independencia", "Paracas", "San Andrés", "San Clemente", "Túpac Amaru Inca"] },
    ],
  },
  {
    name: "Junín",
    provinces: [
      { name: "Huancayo", districts: ["Huancayo", "Carhuacallanga", "Chacapampa", "Chicche", "Chilca", "Chongos Alto", "Chupuro", "Colca", "Cullhuas", "El Tambo", "Huacrapuquio", "Hualhuas", "Huancán", "Huasicancha", "Huayucachi", "Ingenio", "Pariahuanca", "Pilcomayo", "Pucará", "Quichuay", "Quilcas", "San Agustín", "San Jerónimo de Tunán", "San Pedro de Saño", "Santo Domingo de Acobamba", "Sapallanga", "Sicaya", "Viques"] },
      { name: "Concepción", districts: ["Concepción", "Aco", "Andamarca", "Chambará", "Cochas", "Comas", "Heroínas Toledo", "Manzanares", "Mariscal Castilla", "Matahuasi", "Mito", "Nueve de Julio", "Orcotuna", "San José de Quero", "Santa Rosa de Ocopa"] },
      { name: "Chanchamayo", districts: ["Chanchamayo", "Perené", "Pichanaqui", "San Luis de Shuaro", "San Ramón", "Vítoc"] },
      { name: "Jauja", districts: ["Jauja", "Acolla", "Apata", "Ataura", "Canchayllo", "Curicaca", "El Mantaro", "Huamalí", "Huaripampa", "Huertas", "Janjaillo", "Julcán", "Leonor Ordóñez", "Llocllapampa", "Marco", "Masma", "Masma Chicche", "Molinos", "Monobamba", "Muqui", "Muquiyauyo", "Paca", "Paccha", "Pancán", "Parco", "Pomacancha", "Ricrán", "San Lorenzo", "San Pedro de Chunán", "Sausa", "Sincos", "Tunanmarca", "Yauli", "Yauyos"] },
      { name: "Junín", districts: ["Junín", "Carhuamayo", "Ondores", "Ulcumayo"] },
      { name: "Satipo", districts: ["Satipo", "Coviriali", "Llaylla", "Mazamari", "Pampa Hermosa", "Pangoa", "Río Negro", "Río Tambo", "Vizcatán del Ene"] },
      { name: "Tarma", districts: ["Tarma", "Acobamba", "Huaricolca", "Huasahuasi", "La Unión", "Palca", "Palcamayo", "San Pedro de Cajas", "Tapo"] },
      { name: "Yauli", districts: ["La Oroya", "Chacapalpa", "Huay-Huay", "Marcapomacocha", "Morococha", "Paccha", "Santa Bárbara de Carhuacayán", "Santa Rosa de Sacco", "Suitucancha", "Yauli"] },
      { name: "Chupaca", districts: ["Chupaca", "Ahuac", "Chongos Bajo", "Huachac", "Huamancaca Chico", "San Juan de Iscos", "San Juan de Jarpa", "Tres de Diciembre", "Yanacancha"] },
    ],
  },
  {
    name: "La Libertad",
    provinces: [
      { name: "Trujillo", districts: ["Trujillo", "El Porvenir", "Florencia de Mora", "Huanchaco", "La Esperanza", "Laredo", "Moche", "Poroto", "Salaverry", "Simbal", "Víctor Larco Herrera"] },
      { name: "Ascope", districts: ["Ascope", "Chicama", "Chocope", "Magdalena de Cao", "Paiján", "Rázuri", "Santiago de Cao", "Casa Grande"] },
      { name: "Bolívar", districts: ["Bolívar", "Bambamarca", "Condormarca", "Longotea", "Uchumarca", "Ucuncha"] },
      { name: "Chepén", districts: ["Chepén", "Pacanga", "Pueblo Nuevo"] },
      { name: "Julcán", districts: ["Julcán", "Calamarca", "Carabamba", "Huaso"] },
      { name: "Otuzco", districts: ["Otuzco", "Agallpampa", "Charat", "Huaranchal", "La Cuesta", "Mache", "Paranday", "Salpo", "Sinsicap", "Usquil"] },
      { name: "Pacasmayo", districts: ["San Pedro de Lloc", "Guadalupe", "Jequetepeque", "Pacasmayo", "San José"] },
      { name: "Pataz", districts: ["Tayabamba", "Buldibuyo", "Chillia", "Huancaspata", "Huaylillas", "Huayo", "Ongón", "Parcoy", "Pataz", "Pías", "Santiago de Challas", "Taurija", "Urpay"] },
      { name: "Sánchez Carrión", districts: ["Huamachuco", "Chugay", "Cochorco", "Curgos", "Marcabal", "Sanagorán", "Sarín", "Sartimbamba"] },
      { name: "Santiago de Chuco", districts: ["Santiago de Chuco", "Angasmarca", "Cachicadán", "Mollebamba", "Mollepata", "Quiruvilca", "Santa Cruz de Chuca", "Sitabamba"] },
      { name: "Gran Chimú", districts: ["Cascas", "Lucma", "Marmot", "Sayapullo"] },
      { name: "Virú", districts: ["Virú", "Chao", "Guadalupito"] },
    ],
  },
  {
    name: "Lambayeque",
    provinces: [
      { name: "Chiclayo", districts: ["Chiclayo", "Chongoyape", "Eten", "Eten Puerto", "José Leonardo Ortiz", "La Victoria", "Lagunas", "Monsefú", "Nueva Arica", "Oyotún", "Picsi", "Pimentel", "Reque", "Santa Rosa", "Saña", "Cayaltí", "Pátapo", "Pomalca", "Pucalá", "Tumán"] },
      { name: "Ferreñafe", districts: ["Ferreñafe", "Cañaris", "Incahuasi", "Manuel Antonio Mesones Muro", "Pítipo", "Pueblo Nuevo"] },
      { name: "Lambayeque", districts: ["Lambayeque", "Chóchope", "Íllimo", "Jayanca", "Mochumí", "Mórrope", "Motupe", "Olmos", "Pacora", "Salas", "San José", "Túcume"] },
    ],
  },
  {
    name: "Lima",
    provinces: [
      { name: "Lima", districts: ["Lima", "Ancón", "Ate", "Barranco", "Breña", "Carabayllo", "Chaclacayo", "Chorrillos", "Cieneguilla", "Comas", "El Agustino", "Independencia", "Jesús María", "La Molina", "La Victoria", "Lince", "Los Olivos", "Lurigancho", "Lurín", "Magdalena del Mar", "Miraflores", "Pachacámac", "Pucusana", "Pueblo Libre", "Puente Piedra", "Punta Hermosa", "Punta Negra", "Rímac", "San Bartolo", "San Borja", "San Isidro", "San Juan de Lurigancho", "San Juan de Miraflores", "San Luis", "San Martín de Porres", "San Miguel", "Santa Anita", "Santa María del Mar", "Santa Rosa", "Santiago de Surco", "Surquillo", "Villa El Salvador", "Villa María del Triunfo"] },
      { name: "Barranca", districts: ["Barranca", "Paramonga", "Pativilca", "Supe", "Supe Puerto"] },
      { name: "Cajatambo", districts: ["Cajatambo", "Copa", "Gorgor", "Huancapón", "Manás"] },
      { name: "Canta", districts: ["Canta", "Arahuay", "Huamantanga", "Huaros", "Lachaqui", "San Buenaventura", "Santa Rosa de Quives"] },
      { name: "Cañete", districts: ["San Vicente de Cañete", "Asia", "Calango", "Cerro Azul", "Chilca", "Coayllo", "Imperial", "Lunahuaná", "Mala", "Nuevo Imperial", "Pacarán", "Quilmaná", "San Antonio", "San Luis", "Santa Cruz de Flores", "Zúñiga"] },
      { name: "Huaral", districts: ["Huaral", "Atavillos Alto", "Atavillos Bajo", "Aucallama", "Chancay", "Ihuarí", "Lampían", "Pacaraos", "San Miguel de Acos", "Santa Cruz de Andamarca", "Sumbilca", "Veintisiete de Noviembre"] },
      { name: "Huarochirí", districts: ["Matucana", "Antioquía", "Callahuanca", "Carampoma", "Chicla", "Cuenca", "Huachupampa", "Huanza", "Huarochirí", "Lahuaytambo", "Langa", "Laraos", "Mariatana", "Ricardo Palma", "San Andrés de Tupicocha", "San Antonio", "San Bartolomé", "San Damián", "San Juan de Iris", "San Juan de Tantaranche", "San Lorenzo de Quinti", "San Mateo", "San Mateo de Otao", "San Pedro de Casta", "San Pedro de Huancayre", "Sangallaya", "Santa Cruz de Cocachacra", "Santa Eulalia", "Santiago de Anchucaya", "Santiago de Tuna", "Santo Domingo de los Olleros", "Surco"] },
      { name: "Huaura", districts: ["Huacho", "Ámbar", "Caleta de Carquín", "Checras", "Hualmay", "Huaura", "Leoncio Prado", "Paccho", "Santa Leonor", "Santa María", "Sayán", "Végueta"] },
      { name: "Oyón", districts: ["Oyón", "Andajes", "Caujul", "Cochamarca", "Naván", "Pachangara"] },
      { name: "Yauyos", districts: ["Yauyos", "Alis", "Ayauca", "Ayaviri", "Azángaro", "Cacra", "Carania", "Catahuasi", "Chocos", "Cochas", "Colonia", "Hongos", "Huampara", "Huancaya", "Huangáscar", "Huantán", "Laraos", "Lincha", "Madeán", "Miraflores", "Omas", "Putinza", "Quinches", "Quinocay", "San Joaquín", "San Pedro de Pilas", "Tanta", "Tauripampa", "Tomas", "Tupe", "Viñac", "Vitis"] },
    ],
  },
  {
    name: "Loreto",
    provinces: [
      { name: "Maynas", districts: ["Iquitos", "Alto Nanay", "Fernando Lores", "Indiana", "Las Amazonas", "Mazán", "Napo", "Punchana", "Putumayo", "Torres Causana", "Belén", "San Juan Bautista"] },
      { name: "Alto Amazonas", districts: ["Yurimaguas", "Balsapuerto", "Jeberos", "Lagunas", "Santa Cruz", "Teniente César López Rojas"] },
      { name: "Loreto", districts: ["Nauta", "Parinari", "Tigre", "Trompeteros", "Urarinas"] },
      { name: "Mariscal Ramón Castilla", districts: ["Caballococha", "Pebas", "Ramón Castilla", "San Pablo", "Yavarí"] },
      { name: "Putumayo", districts: ["Putumayo", "Rosa Panduro", "Teniente Manuel Clavero", "Yaguas"] },
      { name: "Requena", districts: ["Requena", "Alto Tapiche", "Capelo", "Emilio San Martín", "Maquía", "Puinahua", "Saquena", "Soplin", "Tapiche", "Jenaro Herrera", "Yaquerana"] },
      { name: "Ucayali", districts: ["Contamana", "Inahuaya", "Padre Márquez", "Pampa Hermosa", "Sarayacu", "Vargas Guerra"] },
      { name: "Datem del Marañón", districts: ["San Lorenzo", "Barranca", "Cahuapanas", "Manseriche", "Morona", "Pastaza", "Andoas"] },
    ],
  },
  {
    name: "Madre de Dios",
    provinces: [
      { name: "Tambopata", districts: ["Tambopata", "Inambari", "Las Piedras", "Laberinto"] },
      { name: "Manu", districts: ["Manu", "Fitzcarrald", "Madre de Dios", "Huepetuhe"] },
      { name: "Tahuamanu", districts: ["Iñapari", "Iberia", "Tahuamanu"] },
    ],
  },
  {
    name: "Moquegua",
    provinces: [
      { name: "Mariscal Nieto", districts: ["Moquegua", "Carumas", "Cuchumbaya", "Samegua", "San Cristóbal", "Torata"] },
      { name: "General Sánchez Cerro", districts: ["Omate", "Chojata", "Coalaque", "Ichuña", "La Capilla", "Lloque", "Matalaque", "Puquina", "Quinistaquillas", "Ubinas", "Yunga"] },
      { name: "Ilo", districts: ["Ilo", "El Algarrobal", "Pacocha"] },
    ],
  },
  {
    name: "Pasco",
    provinces: [
      { name: "Pasco", districts: ["Chaupimarca", "Huachón", "Huariaca", "Huayllay", "Ninacaca", "Pallanchacra", "Paucartambo", "San Francisco de Asís de Yarusyacán", "Simón Bolívar", "Ticlacayán", "Tinyahuarco", "Vicco", "Yanacancha"] },
      { name: "Daniel Alcides Carrión", districts: ["Yanahuanca", "Chacayán", "Goyllarisquizga", "Páucar", "San Pedro de Pillao", "Santa Ana de Tusi", "Tápuc", "Vilcabamba"] },
      { name: "Oxapampa", districts: ["Oxapampa", "Chontabamba", "Constitución", "Huancabamba", "Palcazú", "Pozuzo", "Puerto Bermúdez", "Villa Rica"] },
    ],
  },
  {
    name: "Piura",
    provinces: [
      { name: "Piura", districts: ["Piura", "Castilla", "Catacaos", "Cura Mori", "El Tallán", "La Arena", "La Unión", "Las Lomas", "Tambo Grande", "Veintiséis de Octubre"] },
      { name: "Ayabaca", districts: ["Ayabaca", "Frías", "Jililí", "Lagunas", "Montero", "Pacaipampa", "Paimas", "Sapillica", "Sícchez", "Suyo"] },
      { name: "Huancabamba", districts: ["Huancabamba", "Canchaque", "El Carmen de la Frontera", "Huarmaca", "Lalaquiz", "San Miguel de El Faique", "Sóndor", "Sondorillo"] },
      { name: "Morropón", districts: ["Chulucanas", "Buenos Aires", "Chalaco", "La Matanza", "Morropón", "Salitral", "San Juan de Bigote", "Santa Catalina de Mossa", "Santo Domingo", "Yamango"] },
      { name: "Paita", districts: ["Paita", "Amotape", "Arenal", "Colán", "La Huaca", "Tamarindo", "Vichayal"] },
      { name: "Sechura", districts: ["Sechura", "Bellavista de la Unión", "Bernal", "Cristo Nos Valga", "Rinconada Llicuar", "Vice"] },
      { name: "Sullana", districts: ["Sullana", "Bellavista", "Ignacio Escudero", "Lancones", "Marcavelica", "Miguel Checa", "Querecotillo", "Salitral"] },
      { name: "Talara", districts: ["Pariñas", "El Alto", "La Brea", "Lobitos", "Los Órganos", "Máncora"] },
    ],
  },
  {
    name: "Puno",
    provinces: [
      { name: "Puno", districts: ["Puno", "Acora", "Amantaní", "Atuncolla", "Capachica", "Chucuito", "Coata", "Huata", "Mañazo", "Paucarcolla", "Pichacani", "Platería", "San Antonio", "Tiquillaca", "Vilque"] },
      { name: "Azángaro", districts: ["Azángaro", "Achaya", "Arapa", "Asillo", "Caminaca", "Chupa", "José Domingo Choquehuanca", "Muñani", "Potoni", "Samán", "San Antón", "San José", "San Juan de Salinas", "Santiago de Pupuja", "Tirapata"] },
      { name: "Carabaya", districts: ["Macusani", "Ajoyani", "Ayapata", "Coasa", "Corani", "Crucero", "Ituata", "Ollachea", "San Gabán", "Usicayos"] },
      { name: "Chucuito", districts: ["Juli", "Desaguadero", "Huacullani", "Kelluyo", "Pisacoma", "Pomata", "Zepita"] },
      { name: "El Collao", districts: ["Ilave", "Capazo", "Conduriri", "Pilcuyo", "Santa Rosa"] },
      { name: "Huancané", districts: ["Huancané", "Cojata", "Huatasani", "Inchupalla", "Pusi", "Rosaspata", "Taraco", "Vilque Chico"] },
      { name: "Lampa", districts: ["Lampa", "Cabanilla", "Calapuja", "Nicasio", "Ocuviri", "Palca", "Paratía", "Pucará", "Santa Lucía", "Vilavila"] },
      { name: "Melgar", districts: ["Ayaviri", "Antauta", "Cupi", "Llalli", "Macari", "Nuñoa", "Orurillo", "Santa Rosa", "Umachiri"] },
      { name: "Moho", districts: ["Moho", "Conima", "Huayrapata", "Tilali"] },
      { name: "San Antonio de Putina", districts: ["Putina", "Ananea", "Pedro Vilca Apaza", "Quilcapuncu", "Sina"] },
      { name: "San Román", districts: ["Juliaca", "Cabana", "Cabanillas", "Caracoto", "San Miguel"] },
      { name: "Sandia", districts: ["Sandia", "Cuyocuyo", "Limbani", "Patambuco", "Phara", "Quiaca", "San Juan del Oro", "San Pedro de Putina Punco", "Yanahuaya"] },
      { name: "Yunguyo", districts: ["Yunguyo", "Anapia", "Copani", "Cuturapi", "Ollaraya", "Tinicachi", "Unicachi"] },
    ],
  },
  {
    name: "San Martín",
    provinces: [
      { name: "Moyobamba", districts: ["Moyobamba", "Calzada", "Habana", "Jepelacio", "Soritor", "Yantaló"] },
      { name: "Bellavista", districts: ["Bellavista", "Alto Biavo", "Bajo Biavo", "Huallaga", "San Pablo", "San Rafael"] },
      { name: "El Dorado", districts: ["San José de Sisa", "Agua Blanca", "San Martín", "Santa Rosa", "Shatoja"] },
      { name: "Huallaga", districts: ["Saposoa", "Alto Saposoa", "El Eslabón", "Piscoyacu", "Sacanche", "Tingo de Saposoa"] },
      { name: "Lamas", districts: ["Lamas", "Alonso de Alvarado", "Barranquita", "Caynarachi", "Cuñumbuqui", "Pinto Recodo", "Rumisapa", "San Roque de Cumbaza", "Shanao", "Tabalosos", "Zapatero"] },
      { name: "Mariscal Cáceres", districts: ["Juanjuí", "Campanilla", "Huicungo", "Pachiza", "Pajarillo"] },
      { name: "Picota", districts: ["Picota", "Buenos Aires", "Caspisapa", "Pilluana", "Pucacaca", "San Cristóbal", "San Hilarión", "Shamboyacu", "Tingo de Ponaza", "Tres Unidos"] },
      { name: "Rioja", districts: ["Rioja", "Awajún", "Elías Soplín Vargas", "Nueva Cajamarca", "Pardo Miguel", "Posic", "San Fernando", "Yorongos", "Yuracyacu"] },
      { name: "San Martín", districts: ["Tarapoto", "Alberto Leveau", "Cacatachi", "Chazuta", "Chipurana", "El Porvenir", "Huimbayoc", "Juan Guerra", "La Banda de Shilcayo", "Morales", "Papaplaya", "San Antonio", "Sauce", "Shapaja"] },
      { name: "Tocache", districts: ["Tocache", "Nuevo Progreso", "Pólvora", "Shunte", "Uchiza"] },
    ],
  },
  {
    name: "Tacna",
    provinces: [
      { name: "Tacna", districts: ["Tacna", "Alto de la Alianza", "Calana", "Ciudad Nueva", "Coronel Gregorio Albarracín Lanchipa", "Inclán", "Pachía", "Palca", "Pocollay", "Sama"] },
      { name: "Candarave", districts: ["Candarave", "Cairani", "Camilaca", "Curibaya", "Huanuara", "Quilahuani"] },
      { name: "Jorge Basadre", districts: ["Locumba", "Ilabaya", "Ite"] },
      { name: "Tarata", districts: ["Tarata", "Estique", "Estique Pampa", "Héroes Albarracín", "Sitajara", "Susapaya", "Tarucachi", "Ticaco"] },
    ],
  },
  {
    name: "Tumbes",
    provinces: [
      { name: "Tumbes", districts: ["Tumbes", "Corrales", "La Cruz", "Pampas de Hospital", "San Jacinto", "San Juan de la Virgen"] },
      { name: "Contralmirante Villar", districts: ["Zorritos", "Casitas", "Canoas de Punta Sal"] },
      { name: "Zarumilla", districts: ["Zarumilla", "Aguas Verdes", "Matapalo", "Papayal"] },
    ],
  },
  {
    name: "Ucayali",
    provinces: [
      { name: "Coronel Portillo", districts: ["Callería", "Campoverde", "Iparía", "Manantay", "Masisea", "Nueva Requena", "Yarinacocha"] },
      { name: "Atalaya", districts: ["Atalaya", "Raymondi", "Sepahua", "Tahuanía", "Yurúa"] },
      { name: "Padre Abad", districts: ["Padre Abad", "Curimaná", "Irazola", "Neshuya", "Alexander von Humboldt"] },
      { name: "Purús", districts: ["Purús"] },
    ],
  },
];
